const MoviesActionTypes = {
    FETCH_MOVIES_START: "FETCH_MOVIES_START",
    FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
    INCREMENT_PAGE:"INCREMENT_PAGE",
    DECREMENT_PAGE:"DECREMENT_PAGE",
    SELECTED_MOVIE:"SELECTED_MOVIE",
    UNSELECT_MOVIE:"UNSELECT_MOVIE"
   
  };
  
  export default MoviesActionTypes;