const MoviesActionTypes = {
    FETCH_MOVIES_START: "FETCH_MOVIES_START",
    FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
    INCREMENT_PAGE:"INCREMENT_PAGE",
    DECREMENT_PAGE:"DECREMENT_PAGE",
   
  };
  
  export default MoviesActionTypes;